
# failaas skirtas parodyti kaip surinkta informacija per  contract submission service bus isdeliota i html 
def render_contract_html(
    *,
    content: str,
) -> str:
    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Contract</title>

<style>
body {{
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    line-height: 1.6;
    color: #111;
}}

.contract-container {{
    display: block;
}}

.contract-body {{
    display: block;
    margin: 0;
    white-space: pre-wrap;
    word-break: break-word;
    overflow-wrap: anywhere;
    font-size: 16px;
}}

.footer {{
    margin-top: 24px;
    font-size: 12px;
    color: #777;
    text-align: center;
}}

@page {{
    margin: 24mm 16mm 20mm 16mm;
    @bottom-center {{
        content: "Generated by Pacta";
        font-size: 12px;
        color: #777;
    }}
}}

@media print {{
    .footer {{
        display: none;
    }}
}}
</style>
</head>

<body>
<div class="contract-container">
<div class="contract-body">
{content}
</div>

<div class="footer">
Generated by Pacta
</div>
</div>
</body>
</html>
"""
    return html
