from datetime import datetime

def render_contract_html(
    *,
    contract_id: int,
    template_id: int,
    content: str,
    submitted_at: datetime,
)-> str:
    
    submitted_date = submitted_at.strftime("%Y-%m-%d %H:%M")

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Contract #{contract_id}</title>

<style>
body {{
    font-family: Arial, sans-serif;
    margin: 40px;
    line-height: 1.6;
}}

.contract-container {{
    max-width: 800px;
    margin: auto;
}}

.contract-meta {{
    margin-bottom: 30px;
    color: #555;
    font-size: 14px;
}}

.contract-body {{
    white-space: pre-wrap;
    font-size: 16px;
}}

.footer {{
    margin-top: 40px;
    font-size: 12px;
    color: #777;
}}
</style>
</head>

<body>

<div class="contract-container">

<div class="contract-meta">
Contract ID: {contract_id}<br>
Template ID: {template_id}<br>
Submitted at: {submitted_date}
</div>

<div class="contract-body">
{content}
</div>

<div class="footer">
Generated by Pacta
</div>

</div>

</body>
</html>
"""

    return html