from contextlib import contextmanager
from datetime import UTC, datetime
from io import BytesIO

from docx import Document
from fastapi.testclient import TestClient
import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool
from weasyprint import HTML

from app.database import Base, get_db
from app.dependencies.auth import get_current_user
from app.main import app
from app.models.contract_template import ContractTemplate
from app.models.enums import SubmissionStatus, TemplateStatus
from app.models.filled_contract import FilledContract
from app.models.public_link import PublicLink
from app.models.user import User


LONG_CONTRACT_TAIL = "TAIL SECTION: payment obligations survive termination."


def _build_long_contract_content() -> str:
    sections: list[str] = []
    for idx in range(1, 241):
        sections.append(
            f"Section {idx}: This clause is intentionally long to force natural page breaks."
        )
        sections.append(
            "The parties agree that all obligations and warranties remain enforceable."
        )
        if idx % 6 == 0:
            sections.append("")
    sections.append(LONG_CONTRACT_TAIL)
    return "\n".join(sections)


@contextmanager
def _contract_document_context(rendered_content: str):
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    testing_session_local = sessionmaker(
        autocommit=False,
        autoflush=False,
        bind=engine,
    )
    Base.metadata.create_all(bind=engine)

    setup_db = testing_session_local()
    owner = User(email="doc-owner@example.com", hashed_password="hashed")
    setup_db.add(owner)
    setup_db.flush()

    template = ContractTemplate(
        owner_id=owner.id,
        name="Doc Template",
        description="Doc template description",
        content="Template source content",
        status=TemplateStatus.ACTIVE.value,
        is_deleted=False,
    )
    setup_db.add(template)
    setup_db.flush()

    link = PublicLink(
        template_id=template.id,
        token="doc-token",
        expires_at=datetime(2099, 1, 1, tzinfo=UTC),
        is_revoked=False,
    )
    setup_db.add(link)
    setup_db.flush()

    submission = FilledContract(
        template_id=template.id,
        template_version=1,
        link_id=link.id,
        submitted_data={"full_name": "Jonas"},
        rendered_content=rendered_content,
        ip_address="127.0.0.1",
        user_agent="pytest",
        submission_hash="hash-doc-1",
        status=SubmissionStatus.SUBMITTED.value,
    )
    setup_db.add(submission)
    setup_db.commit()
    setup_db.refresh(owner)
    setup_db.refresh(submission)

    owner_id = owner.id
    submission_id = submission.id
    setup_db.close()

    def override_get_db():
        request_db = testing_session_local()
        try:
            yield request_db
        finally:
            request_db.close()

    def override_get_current_user():
        request_db = testing_session_local()
        try:
            return request_db.query(User).filter(User.id == owner_id).first()
        finally:
            request_db.close()

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_current_user] = override_get_current_user
    client = TestClient(app)

    try:
        yield client, submission_id
    finally:
        app.dependency_overrides.clear()
        Base.metadata.drop_all(bind=engine)


@pytest.fixture
def contract_document_ctx():
    with _contract_document_context("This is contract body content.") as ctx:
        yield ctx


@pytest.fixture
def long_contract_document_ctx():
    with _contract_document_context(_build_long_contract_content()) as ctx:
        yield ctx


def test_document_html_excludes_metadata_and_keeps_footer(contract_document_ctx):
    client, submission_id = contract_document_ctx

    response = client.get(f"/contracts/submissions/{submission_id}/document")
    assert response.status_code == 200

    html = response.json()["html"]
    assert "Contract ID" not in html
    assert "Template ID" not in html
    assert "Submitted at" not in html
    assert "Generated by Pacta" in html
    assert "This is contract body content." in html


def test_pdf_endpoint_returns_200_and_non_empty_content(contract_document_ctx):
    client, submission_id = contract_document_ctx

    response = client.get(f"/contracts/submissions/{submission_id}/pdf")
    assert response.status_code == 200
    assert response.headers["content-type"] == "application/pdf"
    assert len(response.content) > 0


def test_docx_endpoint_returns_200_and_non_empty_content(contract_document_ctx):
    client, submission_id = contract_document_ctx

    response = client.get(f"/contracts/submissions/{submission_id}/docx")
    assert response.status_code == 200
    assert (
        response.headers["content-type"]
        == "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
    assert len(response.content) > 0

    document = Document(BytesIO(response.content))
    text = "\n".join(paragraph.text for paragraph in document.paragraphs)
    footer_text = "\n".join(
        paragraph.text for paragraph in document.sections[0].footer.paragraphs
    )
    assert "This is contract body content." in text
    assert "Generated by Pacta" in footer_text


def test_document_html_contains_long_contract_tail_text(long_contract_document_ctx):
    client, submission_id = long_contract_document_ctx

    response = client.get(f"/contracts/submissions/{submission_id}/document")
    assert response.status_code == 200

    html = response.json()["html"]
    assert "Section 1:" in html
    assert LONG_CONTRACT_TAIL in html
    assert "Generated by Pacta" in html


def test_pdf_endpoint_paginates_long_contract(long_contract_document_ctx):
    client, submission_id = long_contract_document_ctx

    response = client.get(f"/contracts/submissions/{submission_id}/pdf")
    assert response.status_code == 200
    assert response.headers["content-type"] == "application/pdf"
    assert len(response.content) > 0

    html_response = client.get(f"/contracts/submissions/{submission_id}/document")
    assert html_response.status_code == 200
    html = html_response.json()["html"]

    rendered_document = HTML(string=html).render()
    assert len(rendered_document.pages) > 1


def test_docx_endpoint_preserves_late_long_content_text(long_contract_document_ctx):
    client, submission_id = long_contract_document_ctx

    response = client.get(f"/contracts/submissions/{submission_id}/docx")
    assert response.status_code == 200
    assert (
        response.headers["content-type"]
        == "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
    assert len(response.content) > 0

    document = Document(BytesIO(response.content))
    body_text = "\n".join(paragraph.text for paragraph in document.paragraphs)
    footer_text = "\n".join(
        paragraph.text for paragraph in document.sections[0].footer.paragraphs
    )
    assert LONG_CONTRACT_TAIL in body_text
    assert "Generated by Pacta" in footer_text
