"""add submitter_email to filled_contracts

Revision ID: 5126fc3e928f
Revises: 6995e5269e25
Create Date: 2026-06-02 16:43:42.450046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5126fc3e928f'
down_revision: Union[str, Sequence[str], None] = '6995e5269e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filled_contracts', sa.Column('submitter_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filled_contracts', 'submitter_email')
    # ### end Alembic commands ###
